# Generated by Django 5.2 on 2025-06-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referred_by',
        ),
    ]
