# Generated by Django 5.2 on 2025-06-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
