# Generated by Django 5.2 on 2025-06-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitem_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_per_unit',
        ),
    ]
