# Generated by Django 5.2 on 2025-06-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_orderitem_final_price_orderitem_price_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_per_unit',
        ),
    ]
