# Generated by Django 5.2 on 2025-07-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_order_applied_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='applied_coupon_code',
        ),
        migrations.AddField(
            model_name='order',
            name='applied_coupon_code_frozen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
